- name: restart nginx
  service: "name={{ nginx_process_name }} state=restarted"
  become: yes

- name: restart firewalld
  service: "name=firewalld state=restarted"
  become: yes

- name: restart fail2ban
  service: "name=fail2ban state=restarted"
  become: yes